apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-dep
  name: test-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-dep
  template:
    metadata:
      labels:
        app: test-dep
    spec:
      containers:
      - image: akilan/akit-ops-app:v3
        name: httpd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-dep
  name: test-dep
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  selector:
    app: test-dep
  type: NodePort

